"use client";

import type { CustomLayout, Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { ReactNode } from "react";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const DefaultLayout: CustomLayout = (Home: ReactNode) => {
  return (
    <>
      <Navbar />
      <main className="bg-base-100">{Home}</main>
      <Footer />
    </>
  );
};
